// portal.config.ts
//
// This file is generated by the Owner Toolkit customizer.
// It carries every choice made in the wizard: business name, brand color,
// background color, business-name font, welcome message, logo, and the
// questions your form asks.
//
// You can edit this file directly for small tweaks. For larger changes
// (adding new questions, reordering, changing types) it's easier to run
// the customizer again at https://theownertoolkit.co and re-download.

export const portalConfig = {
  businessName: "Untitled Portal",
  businessNameFont: "jakarta" as const,
  brandColor: "#111827",
  backgroundColor: "#F9F7F3",
  welcomeMessage:
    "Tell us a little about your project and we'll be in touch within a business day.",
  logo: null,
  fields: [
    { id: "name", type: "short_answer", role: "customer_name", label: "Your name", required: true, enabled: true },
    { id: "email", type: "email", role: "customer_email", label: "Email", required: true, enabled: true },
    { id: "phone", type: "phone", role: "customer_phone", label: "Phone", required: false, enabled: true },
    { id: "company", type: "short_answer", role: "customer_company", label: "Company", required: false, enabled: true },
    { id: "service", type: "short_answer", label: "Service or project type", required: false, enabled: true },
    { id: "project", type: "long_answer", label: "Project details", required: true, enabled: true },
    { id: "budget", type: "short_answer", label: "Budget", required: false, enabled: true },
    { id: "timeline", type: "short_answer", label: "Desired timeline", required: false, enabled: true },
    { id: "files", type: "file_upload", label: "Files", required: false, enabled: true },
    { id: "contact_method", type: "multiple_choice", label: "Preferred contact method", required: false, enabled: true, options: ["Email", "Phone", "Text message"] },
    { id: "anything_else", type: "long_answer", label: "Anything else we should know?", required: false, enabled: true },
  ],
};

export type PortalConfig = typeof portalConfig;
export type PortalField = (typeof portalConfig.fields)[number];
