/**
 * Typed accessor for portal.config.ts (which lives at the repo root and is
 * generated by the Owner Toolkit customizer).
 *
 * Everything in the app that needs the current configuration imports from
 * here so the root file is the single source of truth.
 */

import { portalConfig as raw } from "@/portal.config";
import type { PortalConfigShape } from "./field-types";

export const portalConfig: PortalConfigShape = raw as PortalConfigShape;

export type { PortalConfigShape, PortalField, PortalLogo, FieldType, FieldRole } from "./field-types";
