import type { Inquiry } from "./types";

/**
 * Sample inquiries seeded on the first dashboard visit so the board looks
 * alive during review. Real inquiries replace these when the customer
 * portal posts to Supabase.
 */

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(9 + (n % 8), 15 + (n % 45), 0, 0);
  return d.toISOString();
};

export const SAMPLE_INQUIRIES: Inquiry[] = [
  {
    id: "inq_ashlee",
    status: "new",
    customerName: "Ashlee Morrison",
    email: "ashlee.m@monrovialiving.com",
    phone: "(503) 555-0142",
    serviceType: "Deep cleaning before listing",
    projectDetails:
      "We're listing our 4-bedroom in Alameda next Friday and could really use a full deep clean the day before. Two floors, three bathrooms, hardwoods throughout, and a partially finished basement. Prefer late morning if possible so the kids are at school.",
    budget: "$500 – $1,000",
    timeline: "Before next Friday",
    preferredContact: "Text message",
    files: [{ name: "current-listing-photos.pdf", size: "3.2 MB" }],
    submittedAt: daysAgo(0),
    ownerNotes: "",
  },
  {
    id: "inq_marcus",
    status: "new",
    customerName: "Marcus Bell",
    email: "marcus@brightbakery.co",
    phone: "(415) 555-0113",
    company: "Bright Bakery",
    serviceType: "Brand identity refresh",
    projectDetails:
      "Opening our second location in September and want the branding to feel a little more grown up. Logo, packaging, storefront signage. Open to trying something bolder than what we have now.",
    budget: "$5,000 – $10,000",
    timeline: "Late summer",
    preferredContact: "Email",
    submittedAt: daysAgo(0),
    ownerNotes: "",
  },
  {
    id: "inq_priya",
    status: "new",
    customerName: "Priya Naidu",
    email: "priya.naidu@gmail.com",
    serviceType: "Custom illustration",
    projectDetails:
      "I'm writing a children's book about a small dog who befriends the neighborhood mail carrier and I need 12 full-color illustrations plus a cover. Simple, warm, hand-drawn look.",
    budget: "Flexible",
    timeline: "By end of October",
    preferredContact: "Email",
    submittedAt: daysAgo(1),
    ownerNotes: "",
  },
  {
    id: "inq_sam",
    status: "new",
    customerName: "Sam Reilly",
    email: "sam.reilly@outlook.com",
    phone: "(971) 555-0178",
    serviceType: "Wedding videography",
    projectDetails:
      "Small wedding at Timberline Lodge in September. Roughly 40 guests, ceremony at 4pm, reception until 10. Would love a highlight reel and a longer documentary edit.",
    budget: "$3,000 – $5,000",
    timeline: "September 14",
    preferredContact: "Phone",
    submittedAt: daysAgo(2),
    ownerNotes: "",
  },
  {
    id: "inq_kristine",
    status: "contacted",
    customerName: "Kristine Wolcott",
    email: "kristine.wolcott@gmail.com",
    phone: "(503) 555-0189",
    serviceType: "Recurring monthly cleaning",
    projectDetails:
      "Looking for someone to take over a monthly cleaning we've had for years. Same team ideally. Two floors, one pet.",
    budget: "$380 / month",
    timeline: "Starting next month",
    preferredContact: "Text message",
    submittedAt: daysAgo(3),
    ownerNotes: "Sent a first email — waiting to hear back on the first-Friday cadence.",
  },
  {
    id: "inq_david",
    status: "contacted",
    customerName: "David Chen",
    email: "dchen@chenlaw.example",
    phone: "(206) 555-0121",
    company: "Chen Legal Group",
    serviceType: "Bathroom remodel consultation",
    projectDetails:
      "Two-bathroom remodel in a Craftsman we're restoring. Prefer someone who's worked in older homes and understands the constraints.",
    budget: "$35,000+",
    timeline: "Fall 2026",
    preferredContact: "Email",
    files: [
      { name: "floor-plan-current.pdf", size: "1.8 MB" },
      { name: "inspiration.zip", size: "24 MB" },
    ],
    submittedAt: daysAgo(4),
    ownerNotes: "Emailed back on Monday — asked about the timing constraint.",
  },
  {
    id: "inq_elena",
    status: "contacted",
    customerName: "Elena Volkov",
    email: "elena@homefeltgoods.com",
    company: "Homefelt",
    serviceType: "Product photography",
    projectDetails:
      "40 SKUs, mostly small home goods (candles, ceramics). Need clean white-background product shots and 6-8 styled lifestyle images for a fall relaunch.",
    budget: "$2,500",
    timeline: "Early September",
    preferredContact: "Email",
    submittedAt: daysAgo(5),
    ownerNotes: "",
  },
  {
    id: "inq_chase",
    status: "quoted",
    customerName: "Chase Keenan",
    email: "chase@keenan-build.com",
    phone: "(503) 555-0154",
    company: "Keenan Build",
    serviceType: "Post-construction cleanup",
    projectDetails:
      "Just finished a full remodel on a Sellwood bungalow — needs a complete post-construction clean before handoff to the client next Wednesday.",
    budget: "$800",
    timeline: "By Wednesday",
    preferredContact: "Text message",
    submittedAt: daysAgo(6),
    ownerNotes: "Sent quote for $780. He said he'd confirm by end of day today.",
  },
  {
    id: "inq_lauren",
    status: "quoted",
    customerName: "Lauren Fitzpatrick",
    email: "lauren.f@example.com",
    serviceType: "Recurring bi-weekly service",
    projectDetails:
      "Small townhouse in the Pearl. Two floors, one bathroom. Just moved in and looking to start service every other Tuesday.",
    budget: "$150 / visit",
    timeline: "Starting next week",
    preferredContact: "Email",
    submittedAt: daysAgo(6),
    ownerNotes: "Quoted $145/visit for a 2-hour clean.",
  },
  {
    id: "inq_simone",
    status: "quoted",
    customerName: "Simone Boudreaux",
    email: "simone.b@icloud.com",
    phone: "(504) 555-0170",
    serviceType: "Family portrait session",
    projectDetails:
      "Just moved to Portland and would love an outdoor family session — two adults, three kids, and a very cooperative retriever. Somewhere leafy.",
    budget: "$650",
    timeline: "Before school starts",
    preferredContact: "Text message",
    files: [{ name: "reference-look.jpg", size: "1.1 MB" }],
    submittedAt: daysAgo(8),
    ownerNotes: "Suggested Hoyt Arboretum, 5:30pm shoot. Waiting on date confirmation.",
  },
  {
    id: "inq_marisol",
    status: "booked",
    customerName: "Marisol Ortega",
    email: "marisol.ortega@example.com",
    phone: "(310) 555-0166",
    serviceType: "Interior design consultation",
    projectDetails:
      "Two-hour consult for a mid-century living room and dining room. Mostly need help with furniture layout and paint direction.",
    budget: "$400",
    timeline: "August 12",
    preferredContact: "Email",
    submittedAt: daysAgo(9),
    ownerNotes: "Booked for Aug 12 at 10am. She'll text the day before to confirm.",
  },
  {
    id: "inq_amanda",
    status: "booked",
    customerName: "Amanda Clark",
    email: "amanda@ac-strategy.co",
    company: "AC Strategy",
    serviceType: "Life coaching program",
    projectDetails:
      "Interested in the 8-session package. Focus is on transitioning out of a corporate role and into consulting.",
    budget: "$1,800",
    timeline: "Start in August",
    preferredContact: "Email",
    submittedAt: daysAgo(11),
    ownerNotes: "Kickoff scheduled for Aug 6. Sent intake questionnaire.",
  },
  {
    id: "inq_jordan",
    status: "booked",
    customerName: "Jordan Baxter",
    email: "jbaxter@example.com",
    phone: "(503) 555-0135",
    serviceType: "Personal training package",
    projectDetails:
      "12-session strength training package. Available mornings, ideally Tuesday and Thursday. Recovering from a knee injury so needs to ease in.",
    budget: "$1,200",
    timeline: "Start ASAP",
    preferredContact: "Text message",
    submittedAt: daysAgo(12),
    ownerNotes: "First session tomorrow at 6:30am.",
  },
  {
    id: "inq_rita",
    status: "won",
    customerName: "Rita Solano",
    email: "rita@solanoflorals.example",
    phone: "(503) 555-0128",
    company: "Solano Florals",
    serviceType: "Monthly bookkeeping",
    projectDetails:
      "Small floral studio, roughly 40 monthly transactions. Need clean books for tax season plus a quarterly P&L walk-through.",
    budget: "$300 / month",
    timeline: "Ongoing",
    preferredContact: "Email",
    submittedAt: daysAgo(16),
    ownerNotes: "Onboarded. First set of books delivered July 3.",
  },
  {
    id: "inq_nathan",
    status: "won",
    customerName: "Nathan Kim",
    email: "nathan.kim@example.io",
    company: "Overtone",
    serviceType: "Website copy audit",
    projectDetails:
      "Need a top-to-bottom audit of our marketing site copy plus recommendations. Roughly 12 pages. Prefer a written report over a call.",
    budget: "$1,500",
    timeline: "Delivered",
    preferredContact: "Email",
    submittedAt: daysAgo(19),
    ownerNotes: "Delivered June 24. Loved it — asked for a follow-on for landing pages.",
  },
  {
    id: "inq_michele",
    status: "lost",
    customerName: "Michele Adams",
    email: "michele.adams@example.com",
    phone: "(503) 555-0119",
    serviceType: "Wedding photography",
    projectDetails:
      "Small backyard ceremony in July. Roughly 30 guests. Looking for someone with a warm, film-inspired style.",
    budget: "$2,500",
    timeline: "July 27",
    preferredContact: "Email",
    submittedAt: daysAgo(23),
    ownerNotes: "Went with a friend of the family. Kept the door open for anniversary photos.",
  },
];
